[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
nom.workspace = true
miette.workspace = true
md5 = "0.7.0"

[dev-dependencies]
rstest.workspace = true
