[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
nom.workspace = true
miette.workspace = true
derive_more = { version = "1.0.0", features = ["try_from"] }
bitvec = "1.0.1"
